name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      
      - name: .NET Restore
        run: dotnet restore

      - name: Publish Application
        run: dotnet publish

      - name: Create Velopack Release
        run: |
          dotnet tool install -g Velopack
          dotnet vpk download github --repoUrl https://github.com/${{ github.repository }}
          dotnet vpk pack --packId KCD2-PAK --packVersion 2.0.0 --packDir bin\Publish --mainExe KCD2-PAK.exe --icon icon.ico --shortcuts None

      - name: Get Changelog
        uses: release-flow/keep-a-changelog-action@v3
        id: changelog
        with:
          command: query
          version: latest

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: Releases