name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Changelog
        uses: release-flow/keep-a-changelog-action@v3
        id: changelog
        with:
          command: query
          version: latest

      - name: Echo Changelog
        run: echo "${{ steps.changelog.outputs.release-notes }}" > releaseNotes.md

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: releaseNotes.md
          path: releaseNotes.md