name: Publish Application
run-name: ${{ github.ref_name }}

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Get Tags
        run: |
          $version = "${{ github.ref_name }}".Substring(1)
          $assemblyVersion = "${{ github.ref_name }}".Substring(1) + "." + "${{ github.run_number }}"
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "ASSEMBLYVERSION=$assemblyVersion" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: .NET Restore
        run: |
          dotnet restore
          dotnet tool restore

      - name: Publish Application
        run: dotnet publish /p:AssemblyVersion=$env:ASSEMBLYVERSION /p:Version=$env:VERSION

      - name: Get Changelog
        uses: release-flow/keep-a-changelog-action@v3
        id: changelog
        with:
          command: query
          version: ${{ env.VERSION }}

      - name: Save Changelog
        run: echo "${{ steps.changelog.outputs.release-notes }}" > releaseNotes.md

      - name: Create Velopack Release
        run: |
          dotnet vpk download github --repoUrl https://github.com/${{ github.repository }}
          dotnet vpk pack --packId KCD2-PAK --packVersion $env:VERSION --packDir bin\Publish --mainExe KCD2-PAK.exe --icon icon.ico --shortcuts None --azureTrustedSignFile azureTrustedSignFile.json --releaseNotes releaseNotes.md --packAuthors 7H3LaughingMan --packTitle "KCD2 PAK"
          dotnet vpk upload github --repoUrl https://github.com/${{ github.repository }} --token ${{ secrets.GITHUB_TOKEN }} --publish --releaseName "KCD2 PAK v$env:VERSION" --tag v$env:VERSION
